version: '3.7'
services:
  db:
    container_name: database
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  flask-app:
    container_name: frontend
    build: ./flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
